### ISSUE TITLE
FR: 一点个人使用的建议

### ISSUE THREAD

**Issue by YIRU69** [LightAPIs/ytgdq#1]
真的很开心你能二次开发跟打器
我遇到了一些 问题，反馈一下，希望能改进的更好
1. 我练习打英语文章时，会出现自动将英文的符号变为中文符号，希望能支持跟打英文
2. 在按键统计图中，我得到以下的图，发现键位图1好像不太正确，是否可以做一个热点图，如图2
3. 另外，如果可以，是否可以做一个针对历史记录的数据分析，做一个图表，能够导出历史数据也好
4. 最后，十分感谢
![image](https://user-images.githubusercontent.com/48148292/167969666-0c55c968-6365-48f1-9921-9f207e486ff2.png)
![image](https://user-images.githubusercontent.com/48148292/167970015-751eddd1-0b53-4b3f-aab2-f8efde0b3d49.png)

**Comment by LightAPIs** [comment]
应该能支持跟打纯英文文章的，是不是把底部工具栏上的替换按钮打开了？

键位图应该是对的呀(*至少我记得我当时测试的时候是准确的*)，理论上也是只统计按键而已，一般不会出错。

**Comment by YIRU69** [comment]
@LightAPIs  
作者大大，可以加一个支持英文打字测词的功能吗
你的软件实在太喜欢了，目前在练习英语打字，希望增加这个功能，万分感谢

**Comment by LightAPIs** [comment]
> @LightAPIs 作者大大，可以加一个支持英文打字测词的功能吗 你的软件实在太喜欢了，目前在练习英语打字，希望增加这个功能，万分感谢

我没有专门练习过英文打字，不太清楚英文测词功能具体指什么，因为英文的词汇本身是会用空格间隔的。还是说你的输入方案是英文词汇的码表？

**Comment by YIRU69** [comment]
英文wpm的按词的速度来计算的，而中文的是按字符
希望能一个能测WPM的功能

**Comment by LightAPIs** [comment]
> 英文wpm的按词来计算的，而中文的是按字符 希望能一个能测WPM的功能 英文的一个词按照空格进行分隔，和中文不一样

在维基上对英文 wpm 单位的定义中是将 5 个字符视为一个单词([单词每分钟](https://zh.wikipedia.org/wiki/%E5%96%AE%E8%A9%9E%E6%AF%8F%E5%88%86%E9%90%98))。

**Comment by YIRU69** [comment]
那我理解错了😭
意思就是希望加一个英文的wpm

**Comment by YIRU69** [comment]
@LightAPIs 感谢你的更新，刚刚试了一下，报告一下问题
![image](https://user-images.githubusercontent.com/48148292/178089462-00826c26-b002-4fa1-9ed2-9608762ae94a.png)

**Comment by LightAPIs** [comment]
> @LightAPIs 感谢你的更新，刚刚试了一下，报告一下问题 ![image](https://user-images.githubusercontent.com/48148292/178089462-00826c26-b002-4fa1-9ed2-9608762ae94a.png)

那是故意这样处理的，因为可能有中文和英文混杂的记录，所以平均那一栏统一用 CPM。

**Comment by YIRU69** [comment]
好的，谢谢解惑
